[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  GOLF_API_KEY = "T7OCNDJDDLYQKS2SIHJ32YAL5I"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
